/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lab1

import kotlin.system.measureNanoTime
import kotlin.system.measureTimeMillis

// https://code.sololearn.com/cztq87N9CxGF/#kt
fun Int.isEven() = this and 1 == 0

// https://en.wikipedia.org/wiki/Heap%27s_algorithm
fun <T> generate(k: Int, arr: Array<T>) {
    if (k == 1) {
       println(arr.joinToString(separator = " "))
    } else {
        generate(k-1, arr)
        for(i in 0 until k-1) {
            if(k.isEven()) {
                arr[i] = arr[k-1].also { arr[k-1] = arr[i]}
            } else {
                arr[0] = arr[k-1].also { arr[k-1] = arr[0]}
            }
            generate(k-1, arr)
        }

    }
}

fun main(args: Array<String>) {
    //println(args[0])
    val endNum : Int = args[0].toInt();
    println("Done in " + measureNanoTime { generate(endNum, (1..endNum).toList().toTypedArray()) } + " ns")
}
