/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

/**
 * CSCI 3501 Lab 2
 *
 * @author Paul Friederichsen
 *
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }

    public static <T extends Comparable> boolean isSorted(T[] data) {
        for (int i = 1; i < data.length; i++) {
            if (data[i - 1].compareTo(data[i]) > 0) {
                return false;
            }
        }
        return true;
    }
}
